version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
  db:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: 
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data: