default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres

development:
  <<: *default
  database: rails-api-demo_dev

test:
  <<: *default
  host: db
  database: rails-api-demo_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
